/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import Controle.Calendario;
import apoio.Formatacao;
import dao.FinanceiroDAO;
import entidade.Financeiro;
import entidade.Locacao;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class DlgSalvarFinanceiro extends javax.swing.JDialog {
     

    /**
     * Creates new form DlgSalvarFinanceiro
     */
    public DlgSalvarFinanceiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Financeiro financeiro = new Financeiro();
        financeiro.setDataPagamento(null);
    }
    

    DlgSalvarFinanceiro(Object object, boolean b, IfrLocacao aThis) {
        initComponents();

    }

    DlgSalvarFinanceiro(Object object, boolean b, IfrLocacao aThis, int codigolocacao) {
        initComponents();

    }

    private DlgSalvarFinanceiro(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lblValorLocação = new javax.swing.JLabel();
        tfdValorTotal = new javax.swing.JTextField();
        lblParcelas = new javax.swing.JLabel();
        jspParcelas = new javax.swing.JSpinner();
        lblLocacaoId = new javax.swing.JLabel();
        tfdLocacaoid = new javax.swing.JTextField();
        lblValorParcela = new javax.swing.JLabel();
        tfdValorParcela = new javax.swing.JTextField();
        btnGerarValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salvar Financeiro");

        lblTitulo.setText("Selecione as opções de pagamento");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lblValorLocação.setText("Valor Total");

        tfdValorTotal.setEditable(false);
        tfdValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblParcelas.setText("Parcelas");

        jspParcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        lblLocacaoId.setText("Cod Locação");

        tfdLocacaoid.setEditable(false);

        lblValorParcela.setText("Valor Parcela");

        tfdValorParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdValorParcelaActionPerformed(evt);
            }
        });

        btnGerarValor.setText("Gerar");
        btnGerarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblValorLocação)
                                .addGap(26, 26, 26)
                                .addComponent(tfdValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblParcelas)
                                .addGap(8, 8, 8)
                                .addComponent(jspParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblLocacaoId)
                                        .addGap(34, 34, 34)
                                        .addComponent(tfdLocacaoid, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValorParcela)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfdValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGerarValor)
                                    .addComponent(btnFechar))
                                .addGap(7, 7, 7)))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorLocação)
                    .addComponent(tfdValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParcelas)
                    .addComponent(jspParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorParcela)
                    .addComponent(tfdValorParcela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerarValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvar)
                    .addComponent(lblLocacaoId)
                    .addComponent(tfdLocacaoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Formatacao frmt = new Formatacao();
        Financeiro financeiro = new Financeiro();
        FinanceiroDAO fDAO = new FinanceiroDAO();
        IfrLocacao ifrlocacao = new IfrLocacao();
        ifrlocacao.apagarDados();
        financeiro.setLocacaoid(Integer.parseInt(tfdLocacaoid.getText()));
        if (((Integer) (jspParcelas.getValue()) < 1) || (Integer) (jspParcelas.getValue()) > 3) {
            JOptionPane.showMessageDialog(null, "Digite uma parcela válida! (1-3)");
        } else {
            System.out.println("Valor parcela = " + tfdValorParcela.getText());
            System.out.println("Valor Total = " + tfdValorTotal.getText());
            double diferenca = Double.parseDouble(tfdValorTotal.getText())
                    - ((Double.parseDouble(tfdValorParcela.getText()))
                    * ((Integer) jspParcelas.getValue()));
            int dias = 30; // primeira parcela daqui à 30 dias
            DecimalFormat f = new DecimalFormat("#.##");   
            f.format(diferenca).replace(',', '.');
            System.out.println("Diferença = " + diferenca);
            financeiro.setDataVencimento(new Calendario().obterDataAtualMais(dias));
            financeiro.setValorPrestacao(diferenca + (Double.parseDouble(tfdValorParcela.getText())));
            financeiro.setSituacao("N");
            System.out.println("Valor dps pa = " + financeiro.getValorPrestacao());

            //salvar parcela no banco
            fDAO.excluiParcelas(Integer.parseInt(tfdLocacaoid.getText()));
            String resultado = fDAO.salvar(financeiro);
            System.out.println("Passou Aqui!");
            if (resultado == null) {
                System.out.println(resultado);
            } else {
                System.out.println(resultado);
            }
            dias += 31; // aumenta um mês
            System.out.println(" Aqui tbm passou!");
            for (int i = 1; i < (Integer) (jspParcelas.getValue()); i++) {
                financeiro.setDataVencimento(new Calendario().obterDataAtualMais(dias));
                financeiro.setValorPrestacao((Double.parseDouble(tfdValorParcela.getText())));
                financeiro.setSituacao("N");

                //salvar parcela no banco
                System.out.println("Para aqui");
                resultado = fDAO.salvar(financeiro);
                System.out.println("Passando");
                if (resultado == null) {
                    System.out.println(resultado);
                } else {
                    System.out.println(resultado);
                }

                dias += 31; // aumenta um mês
            }
             JOptionPane.showMessageDialog(null, "Financeiro gerado com sucesso!");
            
        }
        
        
        this.dispose();


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnGerarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarValorActionPerformed
        double valor = (Double.parseDouble(tfdValorTotal.getText())) / ((Integer) jspParcelas.getValue());
       DecimalFormat f = new DecimalFormat("#.##");
       
        tfdValorParcela.setText(f.format(valor).replace(',', '.'));
        


    }//GEN-LAST:event_btnGerarValorActionPerformed

    private void tfdValorParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdValorParcelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdValorParcelaActionPerformed

    /*public void definirFinanceiro(String data) {
        Financeiro financeiro = new Financeiro();
        FinanceiroDAO fDAO = new FinanceiroDAO();

    } */
    public void definirValorTotal(String valortotal, int idlocacao) {
        tfdValorTotal.setText(valortotal);
        tfdLocacaoid.setText(idlocacao + "");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgSalvarFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgSalvarFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgSalvarFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgSalvarFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgSalvarFinanceiro dialog = new DlgSalvarFinanceiro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerarValor;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JSpinner jspParcelas;
    private javax.swing.JLabel lblLocacaoId;
    private javax.swing.JLabel lblParcelas;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorLocação;
    private javax.swing.JLabel lblValorParcela;
    private javax.swing.JTextField tfdLocacaoid;
    private javax.swing.JTextField tfdValorParcela;
    private javax.swing.JTextField tfdValorTotal;
    // End of variables declaration//GEN-END:variables
}
