/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.Formatacao;
import apoio.Validacao;
import dao.LocacaoDAO;
import dao.LocacaoEquipamentoDAO;
import entidade.Locacao;
import entidade.LocacaoEquipamento;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.postgresql.util.PSQLException;

/**
 *
 * @author Eduardo
 */
public class IfrLocacao extends javax.swing.JInternalFrame {

    double valortotal = 0;
    int id_locacao = 0;
    int id_eqp = 0;

    /**
     * Creates new form IfrLocacao
     */
    public IfrLocacao() {
        initComponents();
        Formatacao.formatarData(tffDataFim);
        Formatacao.formatarData(tffDataInicio);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDataInicio = new javax.swing.JLabel();
        lblDataFim = new javax.swing.JLabel();
        lblDescricao = new javax.swing.JLabel();
        tfdProfissional = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        tfdValorTotal = new javax.swing.JTextField();
        lblDataInicio1 = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        btnFechar = new javax.swing.JButton();
        lblEquipamento = new javax.swing.JLabel();
        lblQuantidade = new javax.swing.JLabel();
        tfdQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisarEquipamento = new javax.swing.JTable();
        lblQuantidade1 = new javax.swing.JLabel();
        tfdCodigoEquipamento = new javax.swing.JTextField();
        lblQuantidade2 = new javax.swing.JLabel();
        btnPesquisarEquipamento = new javax.swing.JButton();
        tfdDescricao = new javax.swing.JTextField();
        btnPesquisarProfissional = new javax.swing.JButton();
        btnSalvarEquipamentos = new javax.swing.JButton();
        btnPesquisarCliente = new javax.swing.JButton();
        tfdCliente = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        lblCodcliente = new javax.swing.JLabel();
        tfdCodcliente = new javax.swing.JTextField();
        lblCodProfissional = new javax.swing.JLabel();
        tfdCodprofissional = new javax.swing.JTextField();
        btnAdicionarEquipamento = new javax.swing.JButton();
        lblValorEquipamento = new javax.swing.JLabel();
        tfdValorEquipamento = new javax.swing.JTextField();
        lblObs = new javax.swing.JLabel();
        lblProfissional1 = new javax.swing.JLabel();
        tfdLocacaoDescricao = new javax.swing.JTextField();
        btnPesquisarLocacao = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        tffDataInicio = new javax.swing.JFormattedTextField();
        tffDataFim = new javax.swing.JFormattedTextField();
        lblAviso2 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();

        setClosable(true);
        setTitle("Locação");

        lblDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataInicio.setText("Cliente*");

        lblDataFim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataFim.setText("Data fim");

        lblDescricao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescricao.setText("Descrição");

        tfdProfissional.setEditable(false);

        lblValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValor.setText("Valor Total");

        tfdValorTotal.setEditable(false);
        tfdValorTotal.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tfdValorTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfdValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdValorTotalActionPerformed(evt);
            }
        });

        lblDataInicio1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDataInicio1.setText("Data ínicio*");

        lblEndereco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEndereco.setText("Endereço*");

        tfdEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdEnderecoActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lblEquipamento.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblEquipamento.setText("Equipamento");

        lblQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantidade.setText("Quantidade*");

        tfdQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdQuantidadeActionPerformed(evt);
            }
        });

        tblPesquisarEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Valor"
            }
        ));
        jScrollPane1.setViewportView(tblPesquisarEquipamento);

        lblQuantidade1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantidade1.setText("Código*");

        lblQuantidade2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuantidade2.setText("Descrição*");

        btnPesquisarEquipamento.setText("Pesquisar");
        btnPesquisarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarEquipamentoActionPerformed(evt);
            }
        });

        btnPesquisarProfissional.setText("Pesquisar");
        btnPesquisarProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProfissionalActionPerformed(evt);
            }
        });

        btnSalvarEquipamentos.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnSalvarEquipamentos.setText("Salvar");
        btnSalvarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEquipamentosActionPerformed(evt);
            }
        });

        btnPesquisarCliente.setText("Pesquisar");
        btnPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarClienteActionPerformed(evt);
            }
        });

        tfdCliente.setEditable(false);
        tfdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdClienteActionPerformed(evt);
            }
        });

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        lblCodcliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodcliente.setText("Código*");

        tfdCodcliente.setEditable(false);

        lblCodProfissional.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCodProfissional.setText("Código*");

        tfdCodprofissional.setEditable(false);
        tfdCodprofissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCodprofissionalActionPerformed(evt);
            }
        });

        btnAdicionarEquipamento.setText("Adicionar");
        btnAdicionarEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarEquipamentoActionPerformed(evt);
            }
        });

        lblValorEquipamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValorEquipamento.setText("Valor");

        tfdValorEquipamento.setEditable(false);
        tfdValorEquipamento.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        tfdValorEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdValorEquipamentoActionPerformed(evt);
            }
        });

        lblObs.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblObs.setText("*Obs: Preencha os Campos Obrigatórios!");

        lblProfissional1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProfissional1.setText("Profissional*");

        tfdLocacaoDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdLocacaoDescricaoActionPerformed(evt);
            }
        });

        btnPesquisarLocacao.setText("Pesquisar Locação Existente");
        btnPesquisarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarLocacaoActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tffDataFim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tffDataFimActionPerformed(evt);
            }
        });

        lblAviso2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblAviso2.setText("*O Cliente deve estar cadastrado!");

        btnReset.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnReset.setText("Nova Locação");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblObs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarEquipamentos)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar)))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataInicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEndereco)
                                            .addComponent(lblDataInicio)
                                            .addComponent(lblQuantidade)
                                            .addComponent(lblQuantidade1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(tfdQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfdCodigoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblValorEquipamento)
                                                    .addComponent(lblQuantidade2))
                                                .addGap(31, 31, 31)
                                                .addComponent(tfdValorEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(213, 213, 213))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(lblCodcliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdCodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisarCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescricao)
                                    .addComponent(lblProfissional1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfdLocacaoDescricao, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tffDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblDataFim)
                                                .addGap(18, 18, 18)
                                                .addComponent(tffDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(tfdProfissional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblCodProfissional)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfdCodprofissional, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPesquisarProfissional))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btnPesquisarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(btnAdicionarEquipamento)
                                                        .addGap(221, 221, 221))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                .addComponent(btnPesquisarEquipamento)))))))
                        .addGap(55, 55, 55))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(lblEquipamento))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAviso2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicio)
                    .addComponent(tfdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarCliente)
                    .addComponent(lblCodcliente)
                    .addComponent(tfdCodcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataInicio1)
                            .addComponent(lblDataFim)
                            .addComponent(tffDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodProfissional)
                            .addComponent(tfdCodprofissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfissional1)
                            .addComponent(btnPesquisarProfissional)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tffDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescricao)
                    .addComponent(tfdLocacaoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisarLocacao)
                    .addComponent(btnGerar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(lblEquipamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQuantidade1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPesquisarEquipamento)
                        .addComponent(lblQuantidade2)
                        .addComponent(tfdCodigoEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdValorEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfdQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQuantidade)
                    .addComponent(lblValorEquipamento)
                    .addComponent(btnAdicionarEquipamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValor))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnSalvarEquipamentos)
                    .addComponent(btnExcluir)
                    .addComponent(lblObs)
                    .addComponent(btnReset))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarClienteActionPerformed
        DlgPesquisarCliente dlgPesquisarCliente = new DlgPesquisarCliente(null, true, this);
        dlgPesquisarCliente.setVisible(true);
    }//GEN-LAST:event_btnPesquisarClienteActionPerformed

    private void btnPesquisarProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProfissionalActionPerformed
        DlgPesquisarProfissional dlgPesquisarFuncionario = new DlgPesquisarProfissional(null, true, this);
        dlgPesquisarFuncionario.setVisible(true);
    }//GEN-LAST:event_btnPesquisarProfissionalActionPerformed

    private void btnPesquisarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarEquipamentoActionPerformed
        DlgPesquisarEquipamento dlgPesquisarEquipamento = new DlgPesquisarEquipamento(null, true, this);
        dlgPesquisarEquipamento.setVisible(true);
    }//GEN-LAST:event_btnPesquisarEquipamentoActionPerformed

    private void tfdCodprofissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCodprofissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCodprofissionalActionPerformed

    private void btnAdicionarEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEquipamentoActionPerformed
        int idz;
        LocacaoEquipamentoDAO leDAO = new LocacaoEquipamentoDAO();
        LocacaoEquipamento locacaoequipamento = new LocacaoEquipamento();
        Locacao locacao = new Locacao();
        if ("".equals(tfdQuantidade.getText()) || "".equals(tfdCodigoEquipamento.getText()) || "".equals(tfdDescricao.getText())) {
            JOptionPane.showMessageDialog(null, "Preencha os campos Obrigatórios!");
        } else if (Validacao.validaNumero(tfdQuantidade.getText())) {

            DecimalFormat f = new DecimalFormat("#.00");
            //LocacaoEquipamentoDAO leDAO = new LocacaoEquipamentoDAO();
            //LocacaoEquipamento locacaoequipamento = new LocacaoEquipamento();
            //Locacao locacao = new Locacao();

            int codloc = locacao.getId();
            String id = tfdCodigoEquipamento.getText().trim();
            String descricao = tfdDescricao.getText().trim();
            String quantidade = tfdQuantidade.getText();

            double valor1 = Integer.parseInt(tfdValorEquipamento.getText());
            double quantidade1 = Integer.parseInt(tfdQuantidade.getText());
            double result = (valor1 * quantidade1);
            /*DefaultTableModel val = (DefaultTableModel) tblPesquisarEquipamento.getModel();
            f.format(result);
            System.out.println("result =" + result);
            val.addRow(new String[]{(Integer.toString(locacaoequipamento.getId())), id, descricao, quantidade, Double.toString(result)});*/
            valortotal = (result + valortotal);
            tfdValorTotal.setText(Double.toString(valortotal));

            System.out.println("ID locacao:" + id_locacao);
            System.out.println("ID eqppp = " + id_eqp);
            locacaoequipamento.setId(id_eqp);
            locacaoequipamento.setEquipamentoId(Integer.parseInt(tfdCodigoEquipamento.getText()));
            locacaoequipamento.setQuantidade(Integer.parseInt(tfdQuantidade.getText()));
            locacaoequipamento.setLocacaoId(id_locacao);
            locacaoequipamento.setValorLocacao(Double.parseDouble(tfdValorTotal.getText()));

            JOptionPane.showMessageDialog(null, leDAO.salvar(locacaoequipamento));

            DefaultTableModel val = (DefaultTableModel) tblPesquisarEquipamento.getModel();
            f.format(result);
            System.out.println("result =" + result);
            System.out.println("id eqp = " + locacaoequipamento.getId());
            val.addRow(new String[]{(Integer.toString(leDAO.ultimoIDInserido())), id, descricao, quantidade, Double.toString(result)});

            tfdCodigoEquipamento.setText("");
            tfdDescricao.setText("");
            tfdQuantidade.setText("");
            tfdValorEquipamento.setText("");

            tfdDescricao.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Digite apenas números!");
        }
        System.out.println("id eqp = " + locacaoequipamento.getId());
    }//GEN-LAST:event_btnAdicionarEquipamentoActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed

        try {
            Locacao locacao = new Locacao();
            //popular o obj
            locacao.setId(id_locacao);
            locacao.setEndereco(tfdEndereco.getText());
            locacao.setDescricao(tfdLocacaoDescricao.getText());
            locacao.setDataInicio(tffDataInicio.getText());
            if (tffDataFim.getText().trim().length() < 10) {
                locacao.setDataFim("");
            } else {
                locacao.setDataFim(tffDataFim.getText());
            }
            locacao.setPessoaId(tfdCodcliente.getText());
            locacao.setProfissional(tfdCodprofissional.getText());
            //criar instancia locacao
            LocacaoDAO lDAO = new LocacaoDAO();
            // vou mandar salvar
            if ("".equals(tfdCliente.getText()) || "".equals(tfdCodcliente.getText()) || "".equals(tffDataInicio.getText()) || "".equals(tfdEndereco.getText()) || "".equals(tfdProfissional.getText()) || "".equals(tfdCodprofissional.getText())) {
                JOptionPane.showMessageDialog(null, "Preencha os campos Obrigatórios marcados com (  *  )!");
            } else {

                id_locacao = Integer.parseInt(lDAO.salvar(locacao));
                System.out.println("ID loc" + id_locacao);
                JOptionPane.showMessageDialog(null, "Locação/Atualizada com sucesso!");
                // posiciona cursor
                btnPesquisarEquipamento.requestFocus();

            }

        } catch (Exception e) {
            System.out.println(e);

        }


    }//GEN-LAST:event_btnGerarActionPerformed

    private void tfdLocacaoDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdLocacaoDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdLocacaoDescricaoActionPerformed

    private void btnSalvarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEquipamentosActionPerformed
        if (tblPesquisarEquipamento.getRowCount() > 0){
            DlgSalvarFinanceiro dlgSalvarFinanceiro = new DlgSalvarFinanceiro(null, true, this);
            dlgSalvarFinanceiro.setVisible(true);
            dlgSalvarFinanceiro.definirValorTotal(tfdValorTotal.getText(), new LocacaoDAO().ultimoIDInserido());
        } else {
            JOptionPane.showMessageDialog(null, "Crie ou selecione uma locação para continuar!");
        }
    }//GEN-LAST:event_btnSalvarEquipamentosActionPerformed

    private void tfdValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdValorTotalActionPerformed

    private void btnPesquisarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarLocacaoActionPerformed
        DlgPesquisarLocacao dlgPesquisarLocacao = new DlgPesquisarLocacao(null, true, this);
        dlgPesquisarLocacao.setVisible(true);
    }//GEN-LAST:event_btnPesquisarLocacaoActionPerformed

    private void tfdEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdEnderecoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int id = Integer.parseInt(String.valueOf(tblPesquisarEquipamento.getValueAt(tblPesquisarEquipamento.getSelectedRow(), 0)));
        LocacaoEquipamentoDAO leDAO = new LocacaoEquipamentoDAO();
        leDAO.excluir(id);
        new LocacaoEquipamentoDAO().popularTabela(tblPesquisarEquipamento, Integer.toString(id_locacao));
        Double valor;
        valortotal = 0;
        for (int i = 0; i < tblPesquisarEquipamento.getRowCount(); i++) {
            valor = Double.parseDouble(String.valueOf(tblPesquisarEquipamento.getValueAt(i, 4)));
            valortotal = (valortotal + valor);
        }
        tfdValorTotal.setText("" + valortotal);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tfdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdClienteActionPerformed

    private void tffDataFimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tffDataFimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tffDataFimActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        Locacao locacao = new Locacao();
        tfdCliente.setText("");
        tfdCodcliente.setText("");
        tfdLocacaoDescricao.setText("");
        tfdEndereco.setText("");
        tffDataInicio.setText("");
        tffDataFim.setText("");
        tfdCodprofissional.setText("");
        tfdProfissional.setText("");
        valortotal = 0;
        tfdValorEquipamento.setText("");
        tfdCodigoEquipamento.setText("");
        tfdQuantidade.setText("");
        tfdDescricao.setText("");
        locacao.setId(0);
        new LocacaoEquipamentoDAO().popularTabela(tblPesquisarEquipamento, null);
    }//GEN-LAST:event_btnResetActionPerformed

    private void tfdQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdQuantidadeActionPerformed

    private void tfdValorEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdValorEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdValorEquipamentoActionPerformed

    // define valores para codigo e descricao do Item
    public void definirCliente(String nome, String id) {
        tfdCliente.setText(nome);
        tfdCodcliente.setText(id);

        tfdEndereco.requestFocus();
    }

    public void definirEquipamento(String descricao, String id, String valor) {
        tfdDescricao.setText(descricao);
        tfdCodigoEquipamento.setText(id);
        tfdValorEquipamento.setText(valor);

        tfdQuantidade.requestFocus();
    }

    public void definirProfissional(String nome, String id) {
        tfdProfissional.setText(nome);
        tfdCodprofissional.setText(id);

        btnGerar.requestFocus();
    }

    public void definirLocacao(String id, String nome, String clienteid, String descricao, String endereco, String datainicio, String datafim, String profissionalid, String profissionalnome) {
        tfdCliente.setText(nome);
        tfdCodcliente.setText(clienteid);
        tfdLocacaoDescricao.setText(descricao);
        tfdEndereco.setText(endereco);
        tffDataInicio.setText(datainicio);
        tffDataFim.setText(datafim);
        tfdCodprofissional.setText(profissionalid);
        tfdProfissional.setText(profissionalnome);
        valortotal = 0;

        id_locacao = Integer.parseInt(id);
        new LocacaoEquipamentoDAO().popularTabela(tblPesquisarEquipamento, id);
        Double valor;
        for (int i = 0; i < tblPesquisarEquipamento.getRowCount(); i++) {
            valor = Double.parseDouble(String.valueOf(tblPesquisarEquipamento.getValueAt(i, 4)));
            valortotal = (valortotal + valor);
            tfdValorTotal.setText("" + valortotal);
        }

        btnGerar.requestFocus();
    }

    public void apagarDados() {
        Locacao locacao = new Locacao();
        tfdCliente.setText("");
        tfdCodcliente.setText("");
        tfdLocacaoDescricao.setText("");
        tfdEndereco.setText("");
        tffDataInicio.setText("");
        tffDataFim.setText("");
        tfdCodprofissional.setText("");
        tfdProfissional.setText("");
        valortotal = 0;
        tfdValorEquipamento.setText("");
        tfdCodigoEquipamento.setText("");
        tfdQuantidade.setText("");
        tfdDescricao.setText("");
        locacao.setId(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEquipamento;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnPesquisarCliente;
    private javax.swing.JButton btnPesquisarEquipamento;
    private javax.swing.JButton btnPesquisarLocacao;
    private javax.swing.JButton btnPesquisarProfissional;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSalvarEquipamentos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAviso2;
    private javax.swing.JLabel lblCodProfissional;
    private javax.swing.JLabel lblCodcliente;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDataInicio1;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEquipamento;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblProfissional1;
    private javax.swing.JLabel lblQuantidade;
    private javax.swing.JLabel lblQuantidade1;
    private javax.swing.JLabel lblQuantidade2;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblValorEquipamento;
    private javax.swing.JTable tblPesquisarEquipamento;
    private javax.swing.JTextField tfdCliente;
    private javax.swing.JTextField tfdCodcliente;
    private javax.swing.JTextField tfdCodigoEquipamento;
    private javax.swing.JTextField tfdCodprofissional;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdLocacaoDescricao;
    private javax.swing.JTextField tfdProfissional;
    private javax.swing.JTextField tfdQuantidade;
    private javax.swing.JTextField tfdValorEquipamento;
    private javax.swing.JTextField tfdValorTotal;
    private javax.swing.JFormattedTextField tffDataFim;
    private javax.swing.JFormattedTextField tffDataInicio;
    // End of variables declaration//GEN-END:variables
}
