/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import apoio.CriptografiaAES;
import apoio.Validacao;
import dao.EquipamentoDAO;
import dao.UsuarioDAO;
import entidade.Usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class IfrUsuario extends javax.swing.JInternalFrame {

    private int codigo = 0;
    private boolean editavel = false;

    /**
     * Creates new form IfrUsuario
     */
    public IfrUsuario() {
        initComponents();
        tfdUsuario.setEnabled(false);
        pfdSenha.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        painelCadastrar = new javax.swing.JPanel();
        btnFechar = new javax.swing.JButton();
        tfdCadNovo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        tfdUsuario = new javax.swing.JTextField();
        pfdSenha = new javax.swing.JPasswordField();
        btnSalvarCadastro = new javax.swing.JButton();
        lblObs = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        tfdNome = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        tfdEmail = new javax.swing.JTextField();
        tfdTelefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##)#####-####");
            tfdTelefone = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        lblTelefone = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        jcbFuncionario = new javax.swing.JCheckBox();
        btnNovousu = new javax.swing.JButton();
        painelAlterarCadastro = new javax.swing.JPanel();
        lblProcurar = new javax.swing.JLabel();
        tfdPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        tabelaPesquisar = new javax.swing.JScrollPane();
        tabelaPesquisarUsuario = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnEditarSituacao = new javax.swing.JButton();
        btnFecharAltCad = new javax.swing.JButton();

        setTitle("Usuario");

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        tfdCadNovo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tfdCadNovo.setText("Cadastrar");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblUsuario.setText("Usuário:");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setText("Senha:");

        tfdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdUsuarioActionPerformed(evt);
            }
        });

        btnSalvarCadastro.setText("Salvar");
        btnSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroActionPerformed(evt);
            }
        });

        lblObs.setText("Obs: Todos os campos são Obrigatorios.");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("E-mail");

        lblTelefone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTelefone.setText("Telefone");

        lblEndereco.setText("Endereço");

        jcbFuncionario.setText("Funcionário");
        jcbFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbFuncionarioActionPerformed(evt);
            }
        });

        btnNovousu.setText("Limpar ");
        btnNovousu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovousuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelCadastrarLayout = new javax.swing.GroupLayout(painelCadastrar);
        painelCadastrar.setLayout(painelCadastrarLayout);
        painelCadastrarLayout.setHorizontalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastrarLayout.createSequentialGroup()
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCadastrarLayout.createSequentialGroup()
                        .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastrarLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(lblEmail)
                                    .addComponent(lblTelefone)
                                    .addComponent(lblEndereco)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastrarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha)
                                    .addComponent(lblUsuario))))
                        .addGap(18, 18, 18)
                        .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelCadastrarLayout.createSequentialGroup()
                                .addComponent(tfdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbFuncionario))
                            .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelCadastrarLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(btnNovousu)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvarCadastro)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar))))
                    .addGroup(painelCadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblObs))
                    .addGroup(painelCadastrarLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(tfdCadNovo)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        painelCadastrarLayout.setVerticalGroup(
            painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfdCadNovo)
                .addGap(9, 9, 9)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfdNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(tfdEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(tfdTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario)
                    .addComponent(jcbFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(pfdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(painelCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarCadastro)
                    .addComponent(btnFechar)
                    .addComponent(btnNovousu))
                .addGap(39, 39, 39)
                .addComponent(lblObs)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar", painelCadastrar);

        lblProcurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblProcurar.setText("Procurar");

        tfdPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdPesquisarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        tabelaPesquisarUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaPesquisar.setViewportView(tabelaPesquisarUsuario);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEditarSituacao.setText("Editar Situação");
        btnEditarSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarSituacaoActionPerformed(evt);
            }
        });

        btnFecharAltCad.setText("Fechar");
        btnFecharAltCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharAltCadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlterarCadastroLayout = new javax.swing.GroupLayout(painelAlterarCadastro);
        painelAlterarCadastro.setLayout(painelAlterarCadastroLayout);
        painelAlterarCadastroLayout.setHorizontalGroup(
            painelAlterarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabelaPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
            .addGroup(painelAlterarCadastroLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfdPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar)
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(painelAlterarCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addComponent(btnEditarSituacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFecharAltCad)
                .addGap(15, 15, 15))
        );
        painelAlterarCadastroLayout.setVerticalGroup(
            painelAlterarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterarCadastroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(painelAlterarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcurar)
                    .addComponent(tfdPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabelaPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(painelAlterarCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnEditarSituacao)
                    .addComponent(btnFecharAltCad))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Alterar Cadastro", painelAlterarCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setBounds(0, 0, 727, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroActionPerformed
        boolean erro = false;
        try {
            Usuario usuario = new Usuario();
            usuario.setNome(tfdNome.getText());
            usuario.setEndereco(tfdEndereco.getText());
            usuario.setEmail(tfdEmail.getText());
            usuario.setTelefone(tfdTelefone.getText());
            System.out.println(codigo);
            usuario.setCod(codigo);
            usuario.setSituacao('A');
            usuario.setClasse('C');
            UsuarioDAO usuarioDAO = new UsuarioDAO();
            Usuario usuario1 = usuarioDAO.consultarId(codigo);
            String retorno = usuario1.getNome();

            if (jcbFuncionario.isSelected()) {
                usuario.setClasse('F');
                String user = tfdUsuario.getText();
                int tam_senha = pfdSenha.getText().length();
                String senha = CriptografiaAES.encrypt(pfdSenha.getText());
                usuario.setUsuario(user);
                usuario.setSenha(senha);
                if (Validacao.validaUsuario(usuario)) {
                    if (user.length() > 2) {
                        if (tam_senha > 4 || editavel) {

                            if (retorno == null) {
                                codigo = 0;

                            }
                            tfdUsuario.setText("");
                            pfdSenha.setText("");
                            tfdUsuario.requestFocus();

                        } else {
                            erro = true;
                            JOptionPane.showMessageDialog(null, "A senha é precisa ter pelo menos 5 caracteres");
                            pfdSenha.setText("");
                            pfdSenha.requestFocus();
                        }
                    } else {
                        erro = true;
                        JOptionPane.showMessageDialog(null, "Usuário muito curto. Inválido!");
                        tfdUsuario.setText("");
                        tfdUsuario.requestFocus();
                    }
                    if (!erro) {
                        if (codigo == 0) {
                            retorno = usuarioDAO.salvar(usuario);
                            JOptionPane.showMessageDialog(null, retorno);
                            tfdNome.setText("");
                            tfdEndereco.setText("");
                            tfdEmail.setText("");
                            tfdTelefone.setText("");
                            codigo = 0;
                        } else {
                            retorno = usuarioDAO.atualizar(usuario);
                            JOptionPane.showMessageDialog(null, retorno);
                            tfdNome.setText("");
                            tfdEndereco.setText("");
                            tfdEmail.setText("");
                            tfdTelefone.setText("");
                            codigo = 0;
                        }
                    }
                }
            } else {
                if (codigo == 0) {
                    retorno = usuarioDAO.salvar(usuario);
                    JOptionPane.showMessageDialog(null, retorno);
                    tfdNome.setText("");
                    tfdEndereco.setText("");
                    tfdEmail.setText("");
                    tfdTelefone.setText("");
                    codigo = 0;
                } else {
                    retorno = usuarioDAO.atualizar(usuario);
                    JOptionPane.showMessageDialog(null, retorno);
                    tfdNome.setText("");
                    tfdEndereco.setText("");
                    tfdEmail.setText("");
                    tfdTelefone.setText("");
                    codigo = 0;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao salvar cadastro!" + e);

        }


    }//GEN-LAST:event_btnSalvarCadastroActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        new UsuarioDAO().popularTabela(tabelaPesquisarUsuario, tfdPesquisar.getText(), "");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tfdPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdPesquisarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            editavel = true;
            String codigoS = String.valueOf(tabelaPesquisarUsuario.getValueAt(tabelaPesquisarUsuario.getSelectedRow(), 0));
            String classe = String.valueOf(tabelaPesquisarUsuario.getValueAt(tabelaPesquisarUsuario.getSelectedRow(), 5));
            Usuario usuario = new UsuarioDAO().consultarId(Integer.parseInt(codigoS));
            if (usuario != null) {
                jTabbedPane1.setSelectedIndex(0);
                tfdNome.setText(usuario.getNome());
                tfdEndereco.setText(usuario.getEndereco());
                tfdEmail.setText(usuario.getEmail());
                tfdTelefone.setText(usuario.getTelefone());
                codigo = usuario.getCod();
                if (classe.equals("F")) {
                    jcbFuncionario.setSelected(true);
                    tfdUsuario.setEnabled(true);
                    pfdSenha.setEnabled(true);
                    tfdUsuario.setText(usuario.getUsuario());
                    pfdSenha.setText("");
                    tfdUsuario.requestFocus();

                } else {
                    tfdUsuario.setEnabled(false);
                    pfdSenha.setEnabled(false);
                    tfdUsuario.setText("");
                    jcbFuncionario.setSelected(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao consultar registro!");
            }
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Você precisa selecionar um registro para realizar a operação");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnFecharAltCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharAltCadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharAltCadActionPerformed

    private void btnEditarSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarSituacaoActionPerformed
        try {
            String codigoS = String.valueOf(tabelaPesquisarUsuario.getValueAt(tabelaPesquisarUsuario.getSelectedRow(), 0));
            Usuario usuario = new UsuarioDAO().consultarId(Integer.parseInt(codigoS));
            char sit;
            if (usuario.getSituacao() == 'A') {
                sit = 'I';
            } else {
                sit = 'A';
            }
            String retorno = new UsuarioDAO().excluir(Integer.parseInt(codigoS), sit);
            if (retorno != null) {
                JOptionPane.showMessageDialog(null, "Situação alterada com sucesso!");
            }
            //new UsuarioDAO().popularTabela(tabelaPesquisarUsuario, tfdPesquisar.getText(), "" ); // revisar
        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Você precisa selecionar um registro para realizar a operação");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditarSituacaoActionPerformed

    private void tfdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdUsuarioActionPerformed

    private void jcbFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbFuncionarioActionPerformed
        if (jcbFuncionario.isSelected()) {
            tfdUsuario.setEnabled(true);
            pfdSenha.setEnabled(true);
        } else {
            tfdUsuario.setEnabled(false);
            pfdSenha.setEnabled(false);
        }
    }//GEN-LAST:event_jcbFuncionarioActionPerformed

    private void btnNovousuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovousuActionPerformed
        tfdNome.setText("");
        tfdEndereco.setText("");
        tfdEmail.setText("");
        tfdTelefone.setText("");
        codigo = 0;
        tfdUsuario.setEnabled(false);
        pfdSenha.setEnabled(false);
        tfdUsuario.setText("");
        jcbFuncionario.setSelected(false);
    }//GEN-LAST:event_btnNovousuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IfrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IfrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IfrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IfrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IfrUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditarSituacao;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnFecharAltCad;
    private javax.swing.JButton btnNovousu;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvarCadastro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jcbFuncionario;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObs;
    private javax.swing.JLabel lblProcurar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel painelAlterarCadastro;
    private javax.swing.JPanel painelCadastrar;
    private javax.swing.JPasswordField pfdSenha;
    private javax.swing.JScrollPane tabelaPesquisar;
    private javax.swing.JTable tabelaPesquisarUsuario;
    private javax.swing.JLabel tfdCadNovo;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdPesquisar;
    private javax.swing.JTextField tfdTelefone;
    private javax.swing.JTextField tfdUsuario;
    // End of variables declaration//GEN-END:variables
}
